# -*- coding:utf-8 -*-
image_hosts = [
    "http://www.datuimg.com/images.*?.[jpg|jpeg|gif|JPG]",
    "http://img.*?.uploadhouse.com/fileuploads.*?.[jpg|jpeg|gif|JPG]",
    "http://img.*?.showhaotu.com.*?.[jpg|jpeg|gif|JPG]",
    "http://img.*?.showhaotu.xyz.*?.[jpg|jpeg|gif|JPG]",
    "https://img.*?.showhaotu.com.*?.[jpg|jpeg|gif|JPG]",
    "http://s1.s8tu.com.*?.[jpg|jpeg|gif|JPG]",
    "http://p2.imageab.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?ultraimg.com/images.*?.[jpg|jpeg|gif|JPG]",
    "http://img.*?.imagetwist.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?tinypic.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?chuantupian.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?imgur.com.*?.[jpg|jpeg|gif|JPG]",
    "https://.*?media.tumblr.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?imagebam.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?kepkezelo.com/images.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?directupload.net.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?freeimage.us/image.php?id=",
    "http://.*?picpar.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?imgaa.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?imagefruity.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?ihostimg.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?imgspice.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?anony.ws.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?imgs.co.*?.[jpg|jpeg|gif|JPG]",
    "http://imgpr0n.com.*?.[jpg|jpeg|gif|JPG]",
    "http://urpi.cz.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?img-central.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?fullpix.net.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?qpic.ws.*?.[jpg|jpeg|gif|JPG]",
    "https://.*?imgs.co.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?s9tu.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?upics.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?33img.com.*?.[jpg|jpeg|gif|JPG]",
    "https://.*?uploadhouse.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?immage.biz.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?keep4u.ru.*?.[jpg|jpeg|gif|JPG]",

    "http://.*?imagestorming.com/images.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?bigtox.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?ninja.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?showss.net.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?lookpic.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?uploadfr.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?gagr.com.*?.[jpg|jpeg|gif|JPG]",
    "http://.*?1024.photos.*?.[jpg|jpeg|gif|png]",
]

filters = [
    "www.imagestorming.com",
    "bigtox.com",
    "ninja",
    "showss.net",
    "lookpic.com",
    "uploadfr.com",
    "gagr.com",
    "1024.photos",
]

